version: '3.9'

services:
  site:
    container_name: 'axie-stats-dashboard'
    tty: true
    stdin_open: true
    image: 'node:12-alpine'
    volumes:
      - '.:/var/www/site/'
    networks:
      - default

networks:
  default: 
    name: 'axie-stats-dashboard_network'

